export const restaurant = {
  name: 'Olive Kitchen',
  address: 'House 18, Road 7, Banani, Dhaka',
  status: 'Open now',
  pickupTime: '15–20 min',
  deliveryTime: '25–35 min',
  minOrder: 50,
  rating: 4.8,
  reviews: '2.1k',
  phone: '+880 1700 000000',
};

export const categories = [
  'Popular',
  'Appetizers',
  'Main Courses',
  'Pizza',
  'Burgers',
  'Desserts',
  'Beverages',
];

export const sizeOptions = [
  { label: 'Small', extra: 0 },
  { label: 'Medium', extra: 80 },
  { label: 'Large', extra: 140 },
];

export const addOns = [
  { id: 'extra-cheese', name: 'Extra cheese', price: 60 },
  { id: 'spicy-sauce', name: 'Spicy sauce', price: 30 },
  { id: 'garlic-dip', name: 'Garlic dip', price: 45 },
  { id: 'extra-meat', name: 'Extra meat', price: 120 },
];

export const menuItems = [
  {
    id: 'm1',
    name: 'Signature Olive Chicken',
    category: 'Popular',
    price: 420,
    description: 'Tender grilled chicken with olive herb sauce, rice, and fresh salad.',
    emoji: '🍗',
    tag: 'Best seller',
    gradient: 'linear-gradient(135deg, #fff2d8, #ffd08a)',
  },
  {
    id: 'm2',
    name: 'Creamy Mushroom Soup',
    category: 'Appetizers',
    price: 210,
    description: 'Warm mushroom soup finished with cream and crispy garlic crumbs.',
    emoji: '🍲',
    tag: 'Comfort',
    gradient: 'linear-gradient(135deg, #f2eadb, #c8ad88)',
  },
  {
    id: 'm3',
    name: 'Mediterranean Salad',
    category: 'Appetizers',
    price: 260,
    description: 'Crisp lettuce, cucumber, olives, tomato, feta, and lemon dressing.',
    emoji: '🥗',
    tag: 'Fresh',
    gradient: 'linear-gradient(135deg, #e7f9df, #a7d98d)',
  },
  {
    id: 'm4',
    name: 'Beef Cheese Burger',
    category: 'Burgers',
    price: 380,
    description: 'Juicy beef patty, cheddar, caramelised onion, pickles, and house sauce.',
    emoji: '🍔',
    tag: 'Juicy',
    gradient: 'linear-gradient(135deg, #ffe5c2, #d98948)',
  },
  {
    id: 'm5',
    name: 'Margherita Pizza',
    category: 'Pizza',
    price: 550,
    description: 'Classic tomato, mozzarella, basil, olive oil, and thin crust.',
    emoji: '🍕',
    tag: 'Classic',
    gradient: 'linear-gradient(135deg, #ffe1df, #ff9c8b)',
  },
  {
    id: 'm6',
    name: 'Pepperoni Feast Pizza',
    category: 'Pizza',
    price: 690,
    description: 'Loaded pepperoni, mozzarella, chilli flakes, and Italian herbs.',
    emoji: '🍕',
    tag: 'Spicy',
    gradient: 'linear-gradient(135deg, #ffe1c7, #f06e5b)',
  },
  {
    id: 'm7',
    name: 'Moroccan Lamb Rice Bowl',
    category: 'Main Courses',
    price: 640,
    description: 'Slow-cooked lamb, fragrant rice, roasted vegetables, and yoghurt sauce.',
    emoji: '🍛',
    tag: 'Chef pick',
    gradient: 'linear-gradient(135deg, #fff0c7, #deb26b)',
  },
  {
    id: 'm8',
    name: 'Garlic Butter Prawn Pasta',
    category: 'Main Courses',
    price: 590,
    description: 'Prawns tossed with spaghetti, garlic butter, parmesan, and herbs.',
    emoji: '🍝',
    tag: 'Rich',
    gradient: 'linear-gradient(135deg, #fff6df, #ffba71)',
  },
  {
    id: 'm9',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 260,
    description: 'Soft chocolate cake with a molten centre and vanilla cream.',
    emoji: '🍫',
    tag: 'Sweet',
    gradient: 'linear-gradient(135deg, #ead5c7, #815643)',
  },
  {
    id: 'm10',
    name: 'Lemon Mint Cooler',
    category: 'Beverages',
    price: 160,
    description: 'Fresh lemon, mint, crushed ice, and sparkling soda.',
    emoji: '🥤',
    tag: 'Cool',
    gradient: 'linear-gradient(135deg, #dffaf1, #83d6c4)',
  },
  {
    id: 'm11',
    name: 'Caramel Iced Latte',
    category: 'Beverages',
    price: 220,
    description: 'Cold espresso, milk, caramel syrup, and ice.',
    emoji: '☕',
    tag: 'Chilled',
    gradient: 'linear-gradient(135deg, #f3e3ce, #ad7a50)',
  },
  {
    id: 'm12',
    name: 'Crispy Chicken Burger',
    category: 'Burgers',
    price: 350,
    description: 'Crispy chicken fillet, lettuce, cheese, and creamy mayo sauce.',
    emoji: '🍔',
    tag: 'Crunchy',
    gradient: 'linear-gradient(135deg, #fff1c8, #f0a950)',
  },
];
